version: '3'
services:
  web:
    image: php:8.0-apache
    container_name: apache_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
